# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(941, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setContentsMargins(5, 5, 5, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = PlotWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.gridLayout = QtWidgets.QGridLayout(self.main_page)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.dataSelectionGroupBox = QtWidgets.QGroupBox(self.main_page)
        self.dataSelectionGroupBox.setObjectName("dataSelectionGroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dataSelectionGroupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.selectDataButton = QtWidgets.QPushButton(self.dataSelectionGroupBox)
        self.selectDataButton.setObjectName("selectDataButton")
        self.verticalLayout_4.addWidget(self.selectDataButton)
        self.resetSelectDataButton = QtWidgets.QPushButton(self.dataSelectionGroupBox)
        self.resetSelectDataButton.setObjectName("resetSelectDataButton")
        self.verticalLayout_4.addWidget(self.resetSelectDataButton)
        self.gridLayout.addWidget(self.dataSelectionGroupBox, 0, 4, 3, 1)
        self.zoomingGroupBox = QtWidgets.QGroupBox(self.main_page)
        self.zoomingGroupBox.setObjectName("zoomingGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.zoomingGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.zoomButton = QtWidgets.QPushButton(self.zoomingGroupBox)
        self.zoomButton.setObjectName("zoomButton")
        self.verticalLayout_3.addWidget(self.zoomButton)
        self.resetZoomButton = QtWidgets.QPushButton(self.zoomingGroupBox)
        self.resetZoomButton.setObjectName("resetZoomButton")
        self.verticalLayout_3.addWidget(self.resetZoomButton)
        self.gridLayout.addWidget(self.zoomingGroupBox, 0, 3, 3, 1)
        self.drawingGroupBox = QtWidgets.QGroupBox(self.main_page)
        self.drawingGroupBox.setObjectName("drawingGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.drawingGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.drawButton = QtWidgets.QPushButton(self.drawingGroupBox)
        self.drawButton.setObjectName("drawButton")
        self.verticalLayout_2.addWidget(self.drawButton)
        self.resetDrawButton = QtWidgets.QPushButton(self.drawingGroupBox)
        self.resetDrawButton.setObjectName("resetDrawButton")
        self.verticalLayout_2.addWidget(self.resetDrawButton)
        self.gridLayout.addWidget(self.drawingGroupBox, 0, 2, 3, 1)
        self.label = QtWidgets.QLabel(self.main_page)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.main_page)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 0, 1, 1)
        self.collapseButton = QtWidgets.QPushButton(self.main_page)
        self.collapseButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/collapse-down-4x.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.collapseButton.setIcon(icon)
        self.collapseButton.setObjectName("collapseButton")
        self.gridLayout.addWidget(self.collapseButton, 2, 5, 1, 1)
        self.camSettingsWidget = QtWidgets.QWidget(self.main_page)
        self.camSettingsWidget.setObjectName("camSettingsWidget")
        self.gridLayout.addWidget(self.camSettingsWidget, 0, 0, 2, 2)
        self.stackedWidget.addWidget(self.main_page)
        self.collapsed_page = QtWidgets.QWidget()
        self.collapsed_page.setObjectName("collapsed_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.collapsed_page)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 1, 1, 1)
        self.extendButton = QtWidgets.QPushButton(self.collapsed_page)
        self.extendButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/collapse-up-4x.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.extendButton.setIcon(icon1)
        self.extendButton.setObjectName("extendButton")
        self.gridLayout_2.addWidget(self.extendButton, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.collapsed_page)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionChoose_camera = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/camera-slr-8x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionChoose_camera.setIcon(icon2)
        self.actionChoose_camera.setObjectName("actionChoose_camera")
        self.actionSave_image = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/pencil-8x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_image.setIcon(icon3)
        self.actionSave_image.setObjectName("actionSave_image")
        self.actionManage_plugins = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/puzzle-piece-8x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionManage_plugins.setIcon(icon4)
        self.actionManage_plugins.setObjectName("actionManage_plugins")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/circle-x-8x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon5)
        self.actionQuit.setObjectName("actionQuit")
        self.actionDraw_lines = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/plus-8x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDraw_lines.setIcon(icon6)
        self.actionDraw_lines.setObjectName("actionDraw_lines")
        self.toolBar.addAction(self.actionChoose_camera)
        self.toolBar.addAction(self.actionSave_image)
        self.toolBar.addAction(self.actionDraw_lines)
        self.toolBar.addAction(self.actionManage_plugins)
        self.toolBar.addAction(self.actionQuit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dataSelectionGroupBox.setTitle(_translate("MainWindow", "data selection"))
        self.selectDataButton.setText(_translate("MainWindow", "select"))
        self.resetSelectDataButton.setText(_translate("MainWindow", "reset"))
        self.zoomingGroupBox.setTitle(_translate("MainWindow", "zooming"))
        self.zoomButton.setText(_translate("MainWindow", "zoom"))
        self.resetZoomButton.setText(_translate("MainWindow", "reset"))
        self.drawingGroupBox.setTitle(_translate("MainWindow", "drawing"))
        self.drawButton.setText(_translate("MainWindow", "draw"))
        self.resetDrawButton.setText(_translate("MainWindow", "erease"))
        self.label.setText(_translate("MainWindow", "Saturation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", " Main view"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionChoose_camera.setText(_translate("MainWindow", "Choose camera"))
        self.actionSave_image.setText(_translate("MainWindow", "Save image"))
        self.actionManage_plugins.setText(_translate("MainWindow", "Manage plugins"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionDraw_lines.setText(_translate("MainWindow", "Draw lines"))

from pyqtgraph import PlotWidget
import ui.resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

