# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(941, 527)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = GraphicsLayoutWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.bottom_settings_widget = QtWidgets.QWidget(self.tab)
        self.bottom_settings_widget.setObjectName("bottom_settings_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.bottom_settings_widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.camSettingsWidget = QtWidgets.QWidget(self.bottom_settings_widget)
        self.camSettingsWidget.setObjectName("camSettingsWidget")
        self.gridLayout.addWidget(self.camSettingsWidget, 0, 0, 1, 2)
        self.zoomingGroupBox = QtWidgets.QGroupBox(self.bottom_settings_widget)
        self.zoomingGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.zoomingGroupBox.setObjectName("zoomingGroupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.zoomingGroupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.zoomButton = QtWidgets.QPushButton(self.zoomingGroupBox)
        self.zoomButton.setCheckable(True)
        self.zoomButton.setObjectName("zoomButton")
        self.verticalLayout_5.addWidget(self.zoomButton)
        self.gridLayout.addWidget(self.zoomingGroupBox, 0, 2, 2, 1)
        self.dataSelectionGroupBox = QtWidgets.QGroupBox(self.bottom_settings_widget)
        self.dataSelectionGroupBox.setObjectName("dataSelectionGroupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.dataSelectionGroupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.selectDataButton = QtWidgets.QPushButton(self.dataSelectionGroupBox)
        self.selectDataButton.setCheckable(True)
        self.selectDataButton.setObjectName("selectDataButton")
        self.verticalLayout_6.addWidget(self.selectDataButton)
        self.resetSelectDataButton = QtWidgets.QPushButton(self.dataSelectionGroupBox)
        self.resetSelectDataButton.setObjectName("resetSelectDataButton")
        self.verticalLayout_6.addWidget(self.resetSelectDataButton)
        self.gridLayout.addWidget(self.dataSelectionGroupBox, 0, 3, 2, 1)
        self.progressBar = QtWidgets.QProgressBar(self.bottom_settings_widget)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 1)
        self.saturation_label = QtWidgets.QLabel(self.bottom_settings_widget)
        self.saturation_label.setObjectName("saturation_label")
        self.gridLayout.addWidget(self.saturation_label, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.bottom_settings_widget)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionChoose_camera = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/ui/camera-slr-8x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionChoose_camera.setIcon(icon)
        self.actionChoose_camera.setObjectName("actionChoose_camera")
        self.actionSave_image = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/ui/pencil-8x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_image.setIcon(icon1)
        self.actionSave_image.setObjectName("actionSave_image")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/ui/circle-x-8x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon2)
        self.actionQuit.setObjectName("actionQuit")
        self.actionDraw_lines = QtWidgets.QAction(MainWindow)
        self.actionDraw_lines.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/ui/plus-8x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDraw_lines.setIcon(icon3)
        self.actionDraw_lines.setObjectName("actionDraw_lines")
        self.actionShow_Settings = QtWidgets.QAction(MainWindow)
        self.actionShow_Settings.setCheckable(True)
        self.actionShow_Settings.setChecked(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/ui/cog-8x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_Settings.setIcon(icon4)
        self.actionShow_Settings.setObjectName("actionShow_Settings")
        self.actionTune_camera_parameters = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/ui/dial-8x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTune_camera_parameters.setIcon(icon5)
        self.actionTune_camera_parameters.setObjectName("actionTune_camera_parameters")
        self.toolBar.addAction(self.actionChoose_camera)
        self.toolBar.addAction(self.actionSave_image)
        self.toolBar.addAction(self.actionDraw_lines)
        self.toolBar.addAction(self.actionShow_Settings)
        self.toolBar.addAction(self.actionTune_camera_parameters)
        self.toolBar.addAction(self.actionQuit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.zoomingGroupBox.setTitle(_translate("MainWindow", "zooming"))
        self.zoomButton.setText(_translate("MainWindow", "zoom"))
        self.dataSelectionGroupBox.setTitle(_translate("MainWindow", "data selection"))
        self.selectDataButton.setText(_translate("MainWindow", "select"))
        self.resetSelectDataButton.setText(_translate("MainWindow", "reset"))
        self.saturation_label.setText(_translate("MainWindow", "Saturation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", " Main view"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionChoose_camera.setText(_translate("MainWindow", "Choose camera"))
        self.actionSave_image.setText(_translate("MainWindow", "Save image"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionDraw_lines.setText(_translate("MainWindow", "Draw lines"))
        self.actionShow_Settings.setText(_translate("MainWindow", "Show Settings"))
        self.actionTune_camera_parameters.setText(_translate("MainWindow", "Camera parameters"))

from pyqtgraph import GraphicsLayoutWidget
import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

